version: "3.9"
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      -  27017:27017
    volumes:
       - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
