version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mi-mongodb
    ports:
      -  27017:27017
    networks:
      - mi-red
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-servidor
    ports:
      - 12001:12001
    env_file:
      - .env
    networks:
      - mi-red
    depends_on:
      - mongo

networks:
  mi-red:
    driver: bridge